### ISSUE TITLE
Config file version (33) is newer than supported version (32)

### ISSUE THREAD

**Issue by Veldkornet** [agileek/hassio-addons#19]
**Describe the bug**
Syncthing no longer starting

```
[start] 20:41:28 INFO: syncthing v1.12.1 "Fermium Flea" (go1.15.6 linux-arm64) teamcity@build.syncthing.net 2020-12-06 12:46:27 UTC
[start] 20:41:28 WARNING: Failed to initialize config: config file version (33) is newer than supported version (32). If this is expected, use -allow-newer-config to override.
[monitor] 20:41:28 INFO: Syncthing exited: exit status 1
```

**To Reproduce**
Install Syncthing

**Expected behavior**
Add-on should start

**Screenshots**

**Runtime (please complete the following information):**
 - Hardware: RPi4
 - OS: hassos
 - Architecture: arm64
 - Home assistant version: 2021.02.0
 - Addon Version: 1.12.1

**Additional context**
N/A

**Comment by MichaelBitard** [comment]
That's because syncthing automatically upgrade itself (and there is no easy way to disable that yet).
It probably upgraded itself, then the hassio addon restarted for whatever reason, and the container started with the original version which is incompatible with the new config format.

Anyway, I just pushed the 1.13.0, it should be fixed now, can you confirm?

**Comment by Veldkornet** [comment]
Yup, works now, thanks!
