### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by bastiaanterhorst** [agileek/hassio-addons#53]
Hi, I'm following the install docs, but they seem unclear to me. If you can help me out, I wouldn't mind submitting a PR to make the docs a bit easier to follow.

After copying the signal-cli config files to my home assistant installation, the readme tells me to: "After that, you can install the hassio signal addon".

How do I do this? I cannot find an official Signal addon in the addon store. I have tried adding your repository as a custom repository, but I get nothing to install when I do that. I also cannot install it with HACS.

How should I install the Signal addon?

Thanks!

**Comment by bastiaanterhorst** [comment]
Never mind, it just took a really long time for your addon to show up after adding the custom repo!

**Comment by MichaelBitard** [comment]
That's strange that it took a really long time, usually it's almost instant...

**Comment by squonk11** [comment]
For me the installation is unclear too. I am running Home Assistant on an RPi3 and I did a manual installation using a Python virtual environment. Due to that it seems that I do not have the usual "Addon-store" in the settings. I also do not have docker running. I managed to install some integrations using HACS. 
I also have a working signal-cli available. With this, I am able to send messages via the command line.
How do I have to proceed in order to install this Signal addon so that I can use "notify.signal" in my automations?

**Comment by MichaelBitard** [comment]
I'm sorry I don't really understand your message, it's a little unclear too
(notice the irony ;)).

I don't think python is involved here, you have 3 steps to do:
- make signal-cli working (and it seems you did that)
- install the custom component (or use the official signal integration)
- install the hassio Addon (with the signal-cli folder copied at the right
location)

**Comment by squonk11** [comment]
To be honest, I am new at homeassistant - so maybe I am not asking the right questions - sorry for that.
When I try to install the official signal integration, it tells me that I mus add it to the configuration.yaml and points me to [this](https://www.home-assistant.io/integrations/signal_messenger) documentation. Here I read that I first have to install the Signal Messenger REST API using [these](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md) instructions. These instructions explain the installation only using either Docker or Home Assistant Add-ons. Both I don't have. I did my Homeassistant installation using a Python virtual environment according to [these](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core) instructions. I asked the maintainer of the signal-cli-rest-api how to install without having Docker and without access to the Homeassistant Add-ons: he told me it is not possible.
Now I am lost.

**Comment by MichaelBitard** [comment]
Thanks, I think I understand better.

From the documentation:
> This is an advanced installation process, and some steps might differ on your system.

I think you should stick to the "official Home Assistant Operating System" installation so you would be able to have hacs addons, updates and stuff which will make your home assistant experience a lot better.

But if you cannot do that, then you can look at what this file does : https://github.com/agileek/hassio-addons/blob/master/signal/Dockerfile and replicate it on your system, that way you may be able to have the equivalent of this addon running outside of docker.

I'm sorry I won't be able to help you further though, that's why we use hacs, so we have a "standard" way of doing this through docker to prevent having to have to debug every user setup ;)

**Comment by squonk11** [comment]
Now I have HACS installed and running. How do I install this repository via HACS? When I try to install it as a custom component (providing the url of this repo) I get the error message `No manifest.json file found 'manifest.json'`. Is there another way to install this repository using HACS? Or is HACS not working correctly for me because I have the Homeassistant running in a Python virtual machine?

**Comment by MichaelBitard** [comment]
HACS is only here to help you install my python plugin, which I think you do not really need.

What you have to do is install the docker addon, the one that allows communication between the home assistant official signal integration (or my custom_component) and the signal-cli written in java.
